### ISSUE TITLE
Wait for Keptn Event `delivery` waits on wrong event type

### ISSUE THREAD

**Issue by pchila** [keptn-sandbox/keptn-azure-devops-extension#69]
**Summary** 
WaitForKeptnEvent task used with type delivery waits for `sh.keptn.event.delivery.finished` instead of waiting for `sh.keptn.event.<stage>.delivery.finished` so it always times out.

**Environment**

* Keptn Version (`keptn version`): 0.12.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A
* Kubernetes version (`kubectl version`): N/A
* Client OS (e.g., Linux, macOS, Windows): N/A
* Client Browser: N/A

**Affected Component**

* [ ] Web UI / Bridge
* [ ] CLI
* [ ] REST API or webhooks
* [ ] User experience
* [ ] Developer experience
* [ ] Deployment/manegement with Helm

**To Reproduce**

Trigger a delivery in the azure pipeline and wait for the event of type `delivery` to finish.

**Expected behavior**

Wait Keptn Event detects that delivery finished
**Current behavior**

Wait Keptn Event task times out even if the delivery finishes within the timeout

**Screenshots**

![image](https://user-images.githubusercontent.com/96178987/152510367-53b59333-34ab-412f-8306-3188d0599612.png)
![image](https://user-images.githubusercontent.com/96178987/152510304-639fb8c2-d723-46bf-8897-f93cc20f5724.png)

**Additional context**

With keptn >= 0.8 and the introduction of sequences the type of event published for delivery changed from  `sh.keptn.event.delivery.*` to `sh.keptn.event.<stage>.delivery.*`.  SendKeptnEvent has been updated (triggering delivery works fine) but the WaitForKeptnEvent `delivery` hasn't, hence the timeout.

**Workaround**
To work around the issue, it's possible to wait for a generic event specifying `<stage>.delivery.finished`, so instead of
```
- task: WaitForKeptnEventTask@2
  inputs:
    keptnApiEndpoint: <some keptn endpoint>
    waitForEventType: 'delivery'
    timeout: '3'
    keptnContextVar: 'keptnContext'
```
we can use
```
- task: WaitForKeptnEventTask@2
  inputs:
    keptnApiEndpoint: <some keptn endpoint>
    waitForEventType: 'generic'
    sequence: '<stage>.delivery'
    timeout: '3'
    keptnContextVar: 'keptnContext'
```
